name: opendata
channels:
  - conda-forge
  - defaults
dependencies:
  - s3fs
  - kerchunk
  - xarray
  - zarr
  - dask
  - cfgrib
  - eccodes
  - netCDF4
  - geopandas
  - requests
  - tqdm
  # for development
  - pytest
  - black
  - flake8
  - mkdocstrings
  - mkdocstrings-python
  - mkdocs-git-revision-date-plugin
  - mkdocs-jupyter
