name: opendata
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - s3fs=2022.05
  - kerchunk
  - xarray
  - zarr
  - dask
  - cfgrib
  - eccodes
  - netCDF4
  - geopandas
  - openpyxl=3.1
  - requests
  - tqdm
  # for development
  - pytest
  - black
  - flake8
  - mkdocstrings
  - mkdocstrings-python
  - mkdocs-git-revision-date-plugin
  - mkdocs-jupyter
  - pip
  - pip: 
    - wget 
    - hydrodataset
