site_name: wis-downloader

repo_name: 'GitLab'

site_url: http://124.93.160.156:18888/zhujianfeng/wis-downloader

repo_url: http://124.93.160.156:18888/zhujianfeng/wis-downloader

# extra_css: []
# extra_javascript: []
# google_analytics: ['UA-36723568-3', 'mkdocs.org']

nav:
    - Home: index.md
    - Installation: installation.md
    - Usage: 
          - Download ALOS_DEM: examples/alos_dem.ipynb
    - API Reference:
          - downloader module: module/downloader.md
          - alos_dem module: module/alos_dem.md
          - ncep_gfs module: module/ncep_gfs.md
#     - Contributing: contributing.md
#     - FAQ: faq.md
#     - Changelog: changelog.md
#     - Report Issues: http://124.93.160.156:18888/zhujianfeng/wis-downloader/issues

# theme:
#     palette:
#         scheme: preference
#     name: material
#     icon:
#         repo: fontawesome/brands/github
#     features:
#         - navigation.instant
#         - search.highlight
#         # - navigation.expand
#         # - navigation.tabs
#     custom_dir: "docs/overrides"
theme: readthedocs

plugins:
    - search
    - mkdocstrings
    - git-revision-date
    - mkdocs-jupyter:
          include_source: True
        #   ignore_h1_titles: True
        #   execute: True
        #   execute_ignore: "*.ipynb"
          
markdown_extensions:
    - attr_list
    - pymdownx.superfences
    - pymdownx.highlight:
          linenums: true
    - toc:
          permalink: true

# watch:
#     - wis_downloader

# extra:
#     analytics:
#         provider: google
#         property: UA-XXXXXXXXX-X

